version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./devops/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./devops/monitoring/prometheus/alert-rules.yml:/etc/prometheus/alert-rules.yml:ro

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      - ./devops/monitoring/alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro

  blackbox:
    image: prom/blackbox-exporter:latest
    ports:
      - "9115:9115"
    volumes:
      - ./devops/monitoring/blackbox/blackbox.yml:/etc/blackbox_exporter/config.yml:ro