sonar.projectKey=pilastversion
sonar.projectName=pilastversion
sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000
sonar.login=sqp_9bc82613242f9fecd98679f096f5c13f275c224a

sonar.sources=backend/src/modules/auth,backend/src/modules/projects,backend/src/modules/service-requests,backend/src/utils,backend/src/jobs
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.test.js

sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/uploads/**,**/.git/**,**/artifacts/**

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info


sonar.sources=backend/src/modules/auth,backend/src/modules/projects,backend/src/modules/service-requests,backend/src/utils,backend/src/jobs,frontend/src
sonar.tests=backend/tests,frontend/src/graja-tests
sonar.test.inclusions=backend/tests/**/*.test.js,frontend/src/graja-tests/**/*.test.js
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info