sonar.projectKey=pilastversion
sonar.projectName=pilastversion
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src
sonar.tests=backend/tests
sonar.test.inclusions=backend/tests/**/*.test.js
sonar.exclusions=**/node_modules/**,**/coverage/**,**/dist/**,**/uploads/**,**/.git/**,**/artifacts/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info