global:
  resolve_timeout: 5m

route:
  receiver: default-receiver
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 30m

receivers:
  - name: default-receiver
    webhook_configs:
      - url: 'http://localhost:5001/alerts'
        send_resolved: true
