module.exports = {
  testEnvironment: 'node',
  roots: ['<rootDir>/tests'],
  collectCoverage: true,
  collectCoverageFrom: [
    'src/modules/auth/**/*.js',
    'src/modules/projects/**/*.js',
    'src/modules/service-requests/**/*.js',
    'src/modules/catalog/**/*.js',
    'src/modules/supplier/**/*.js',
    'src/modules/orders/**/*.js',
    'src/modules/messages/**/*.js',
    'src/modules/artisan/**/*.js',
    'src/modules/search/**/*.js',
    'src/modules/reviews/**/*.js',
    'src/modules/ai-assistant/**/*.js',
    'src/modules/documents/**/*.js',
    'src/modules/admin/**/*.js',
    'src/middleware/authMiddleware.js',
    'src/middleware/roleMiddleware.js',
    'src/middleware/uploadProducts.js',
    'src/utils/notify.js',
    'src/utils/serviceRequestEmail.js',
    'src/utils/apiResponse.js',
    'src/jobs/expireServiceRequests.js',
    '!**/node_modules/**',
    '!**/*.routes.js',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov'],
  clearMocks: true,
  restoreMocks: true,
  verbose: true,
};
