apiVersion: v1
kind: Service
metadata:
  name: bmp-backend
  namespace: bmp-production
  labels:
    app: bmp-backend
spec:
  selector:
    app: bmp-backend
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
