apiVersion: v1
kind: ConfigMap
metadata:
  name: bmp-config
  namespace: bmp-production
data:
  NODE_ENV: "production"
  PORT: "5000"
  CLIENT_ORIGIN: "http://bmp.local"
  APP_BASE_URL: "http://bmp.local"
