apiVersion: v1
kind: ConfigMap
metadata:
  name: bmp-config
  namespace: bmp-production
  labels:
    app: bmp
data:
  CLIENT_ORIGIN: "http://bmp.local"
  NODE_ENV: "production"
  PORT: "5000"
  APP_BASE_URL: "http://bmp.local"
