apiVersion: v1
kind: Service
metadata:
  name: bmp-frontend
  namespace: bmp-production
  labels:
    app: bmp-frontend
spec:
  selector:
    app: bmp-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
