apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bmp-ingress
  namespace: bmp-production
  labels:
    app: bmp
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: bmp.local
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bmp-backend
                port:
                  number: 5000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bmp-frontend
                port:
                  number: 80
