apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: pilastversion
type: Opaque
stringData:
  NODE_ENV: production
  PORT: "5000"
  MONGO_URI: "replace-with-mongodb-uri"
  JWT_SECRET: "replace-with-jwt-secret"
  CLOUDINARY_CLOUD_NAME: "replace-with-cloudinary-name"
  CLOUDINARY_API_KEY: "replace-with-cloudinary-key"
  CLOUDINARY_API_SECRET: "replace-with-cloudinary-secret"
  LIBRETRANSLATE_URL: "http://libretranslate:5000"
  ML_SERVICE_URL: "http://ml-service:8000"
